[package]
name = "impl-lib"
version = "0.1.0"
authors = ["Carter Green <cartergr@usc.edu>"]
edition = "2018"

[lib]
crate_type = ["staticlib"]

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
cbindgen = "0.13.1"
