#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

namespace ffi {

struct String;

struct Demo
{
  bool IsRunning;
  String Name;
};

extern "C" {

const String *name(const Demo *self);

} // extern "C"

} // namespace ffi
